apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: default
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQVpRMkhGRkhNR1pZWTU2Tlk=
  AWS_SECRET_ACCESS_KEY: SWJNNEt6SUphNFZnQk81MWQ3VjNSR3VjM09tV2xTSHQybmJWREpCNg==
