apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-feed
  name: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - image: toan158n/udagram-api-feed:v1
        name: backend-feed
        imagePullPolicy: Always  
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2048Mi"
            cpu: "1000m"
        envFrom:
        - configMapRef:
            name: env-config
        - secretRef:
            name: env-secret
        volumeMounts:
        - name: aws-secret
          mountPath: "/root/.aws/"
          readOnly: true        
      volumes:
      - name: aws-secret
        secret:
          secretName: aws-secret
