apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-user
  name: backend-user
spec:
  type: ClusterIP
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
  selector:
    app: backend-user