apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-feed
  name: backend-feed
spec:
  type: ClusterIP
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
  selector:
    app: backend-feed
